(prelude-require-packages
 '(yasnippet
   js2-mode
   sphinx-doc
   anaconda-mode
   virtualenvwrapper
   ggtags
   dired+
   emmet-mode
   moe-theme
   multiple-cursors
   dockerfile-mode
   slime
   neotree
   py-autopep8
   ag
   highlight-indentation
   clojure-snippets
   company-irony
   ))
