(prelude-require-packages
 '(yasnippet
   js2-mode
   sphinx-doc
   anaconda-mode
   virtualenvwrapper
   ggtags
   dired+
   emmet-mode
   comment-dwim-2
   multiple-cursors
   dockerfile-mode
   slime
   neotree
   py-autopep8
   ag
   clojure-snippets
   company-irony
   material-theme
   exec-path-from-shell
   ))
