(prelude-require-packages
 '(yasnippet
   js2-mode
   sphinx-doc
   anaconda-mode
   virtualenvwrapper
   ggtags
   dired+
   emmet-mode
   comment-dwim-2
   anti-zenburn-theme
   zenburn-theme
   theme-changer
   multiple-cursors
   dockerfile-mode
   slime
   neotree
   py-autopep8
   ag
   clojure-snippets
   company-irony
   ))
